# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pascal/Projets/PRPA/ParallelImages

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pascal/Projets/PRPA/ParallelImages

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pascal/Projets/PRPA/ParallelImages/CMakeFiles /home/pascal/Projets/PRPA/ParallelImages/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pascal/Projets/PRPA/ParallelImages/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sres

# Build rule for target.
sres: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sres
.PHONY : sres

# fast build rule for target.
sres/fast:
	$(MAKE) -f CMakeFiles/sres.dir/build.make CMakeFiles/sres.dir/build
.PHONY : sres/fast

#=============================================================================
# Target rules for targets named StreamFilterApp

# Build rule for target.
StreamFilterApp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StreamFilterApp
.PHONY : StreamFilterApp

# fast build rule for target.
StreamFilterApp/fast:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/build
.PHONY : StreamFilterApp/fast

src/ErodeFilter.o: src/ErodeFilter.cpp.o

.PHONY : src/ErodeFilter.o

# target to build an object file
src/ErodeFilter.cpp.o:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/ErodeFilter.cpp.o
.PHONY : src/ErodeFilter.cpp.o

src/ErodeFilter.i: src/ErodeFilter.cpp.i

.PHONY : src/ErodeFilter.i

# target to preprocess a source file
src/ErodeFilter.cpp.i:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/ErodeFilter.cpp.i
.PHONY : src/ErodeFilter.cpp.i

src/ErodeFilter.s: src/ErodeFilter.cpp.s

.PHONY : src/ErodeFilter.s

# target to generate assembly for a file
src/ErodeFilter.cpp.s:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/ErodeFilter.cpp.s
.PHONY : src/ErodeFilter.cpp.s

src/GaussianRegression.o: src/GaussianRegression.cpp.o

.PHONY : src/GaussianRegression.o

# target to build an object file
src/GaussianRegression.cpp.o:
	$(MAKE) -f CMakeFiles/sres.dir/build.make CMakeFiles/sres.dir/src/GaussianRegression.cpp.o
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/GaussianRegression.cpp.o
.PHONY : src/GaussianRegression.cpp.o

src/GaussianRegression.i: src/GaussianRegression.cpp.i

.PHONY : src/GaussianRegression.i

# target to preprocess a source file
src/GaussianRegression.cpp.i:
	$(MAKE) -f CMakeFiles/sres.dir/build.make CMakeFiles/sres.dir/src/GaussianRegression.cpp.i
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/GaussianRegression.cpp.i
.PHONY : src/GaussianRegression.cpp.i

src/GaussianRegression.s: src/GaussianRegression.cpp.s

.PHONY : src/GaussianRegression.s

# target to generate assembly for a file
src/GaussianRegression.cpp.s:
	$(MAKE) -f CMakeFiles/sres.dir/build.make CMakeFiles/sres.dir/src/GaussianRegression.cpp.s
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/GaussianRegression.cpp.s
.PHONY : src/GaussianRegression.cpp.s

src/SRSingleImageGMM.o: src/SRSingleImageGMM.cpp.o

.PHONY : src/SRSingleImageGMM.o

# target to build an object file
src/SRSingleImageGMM.cpp.o:
	$(MAKE) -f CMakeFiles/sres.dir/build.make CMakeFiles/sres.dir/src/SRSingleImageGMM.cpp.o
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/SRSingleImageGMM.cpp.o
.PHONY : src/SRSingleImageGMM.cpp.o

src/SRSingleImageGMM.i: src/SRSingleImageGMM.cpp.i

.PHONY : src/SRSingleImageGMM.i

# target to preprocess a source file
src/SRSingleImageGMM.cpp.i:
	$(MAKE) -f CMakeFiles/sres.dir/build.make CMakeFiles/sres.dir/src/SRSingleImageGMM.cpp.i
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/SRSingleImageGMM.cpp.i
.PHONY : src/SRSingleImageGMM.cpp.i

src/SRSingleImageGMM.s: src/SRSingleImageGMM.cpp.s

.PHONY : src/SRSingleImageGMM.s

# target to generate assembly for a file
src/SRSingleImageGMM.cpp.s:
	$(MAKE) -f CMakeFiles/sres.dir/build.make CMakeFiles/sres.dir/src/SRSingleImageGMM.cpp.s
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/SRSingleImageGMM.cpp.s
.PHONY : src/SRSingleImageGMM.cpp.s

src/inputFilter.o: src/inputFilter.cpp.o

.PHONY : src/inputFilter.o

# target to build an object file
src/inputFilter.cpp.o:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/inputFilter.cpp.o
.PHONY : src/inputFilter.cpp.o

src/inputFilter.i: src/inputFilter.cpp.i

.PHONY : src/inputFilter.i

# target to preprocess a source file
src/inputFilter.cpp.i:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/inputFilter.cpp.i
.PHONY : src/inputFilter.cpp.i

src/inputFilter.s: src/inputFilter.cpp.s

.PHONY : src/inputFilter.s

# target to generate assembly for a file
src/inputFilter.cpp.s:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/inputFilter.cpp.s
.PHONY : src/inputFilter.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/outputFilter.o: src/outputFilter.cpp.o

.PHONY : src/outputFilter.o

# target to build an object file
src/outputFilter.cpp.o:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/outputFilter.cpp.o
.PHONY : src/outputFilter.cpp.o

src/outputFilter.i: src/outputFilter.cpp.i

.PHONY : src/outputFilter.i

# target to preprocess a source file
src/outputFilter.cpp.i:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/outputFilter.cpp.i
.PHONY : src/outputFilter.cpp.i

src/outputFilter.s: src/outputFilter.cpp.s

.PHONY : src/outputFilter.s

# target to generate assembly for a file
src/outputFilter.cpp.s:
	$(MAKE) -f CMakeFiles/StreamFilterApp.dir/build.make CMakeFiles/StreamFilterApp.dir/src/outputFilter.cpp.s
.PHONY : src/outputFilter.cpp.s

src/single.o: src/single.cpp.o

.PHONY : src/single.o

# target to build an object file
src/single.cpp.o:
	$(MAKE) -f CMakeFiles/sres.dir/build.make CMakeFiles/sres.dir/src/single.cpp.o
.PHONY : src/single.cpp.o

src/single.i: src/single.cpp.i

.PHONY : src/single.i

# target to preprocess a source file
src/single.cpp.i:
	$(MAKE) -f CMakeFiles/sres.dir/build.make CMakeFiles/sres.dir/src/single.cpp.i
.PHONY : src/single.cpp.i

src/single.s: src/single.cpp.s

.PHONY : src/single.s

# target to generate assembly for a file
src/single.cpp.s:
	$(MAKE) -f CMakeFiles/sres.dir/build.make CMakeFiles/sres.dir/src/single.cpp.s
.PHONY : src/single.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sres"
	@echo "... StreamFilterApp"
	@echo "... src/ErodeFilter.o"
	@echo "... src/ErodeFilter.i"
	@echo "... src/ErodeFilter.s"
	@echo "... src/GaussianRegression.o"
	@echo "... src/GaussianRegression.i"
	@echo "... src/GaussianRegression.s"
	@echo "... src/SRSingleImageGMM.o"
	@echo "... src/SRSingleImageGMM.i"
	@echo "... src/SRSingleImageGMM.s"
	@echo "... src/inputFilter.o"
	@echo "... src/inputFilter.i"
	@echo "... src/inputFilter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/outputFilter.o"
	@echo "... src/outputFilter.i"
	@echo "... src/outputFilter.s"
	@echo "... src/single.o"
	@echo "... src/single.i"
	@echo "... src/single.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

